version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(maven)"
    groups:
      selenium:
        patterns:
          - "org.seleniumhq.selenium*"
          - "io.github.bonigarcia*"
      testing:
        patterns:
          - "org.testng*"
          - "io.rest-assured*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
    groups:
      actions:
        patterns:
          - "*"
